.archlinux-image-variables:
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  variables:
    # As of 2022-04-14 the jsoncpp provided by the Arch repo does not include a cmake definition and can't be discovered
    CMAKE_OPTIONS: -DINTERNAL_JSONCPP=ON

#################################################
# Makefile
#################################################

job-archlinux-makefile-gcc:
  extends:
    - .job-makefile-gcc
    - .archlinux-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-gcc rules


job-archlinux-makefile-clang:
  extends:
    - .job-makefile-clang
    - .archlinux-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-clang rules

#################################################
# Ninja
#################################################

job-archlinux-ninja-gcc:
  extends:
    - .job-ninja-gcc
    - .archlinux-image-variables


job-archlinux-ninja-clang:
  extends:
    - .job-ninja-clang
    - .archlinux-image-variables
