.debian9-image-variable: &debian9-image-variable
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON

#################################################
# Makefile
#################################################

job-debian9-makefile-gcc:
  extends: .job-makefile-gcc
  <<: *debian9-image-variable


job-debian9-makefile-clang:
  extends: .job-makefile-clang
  <<: *debian9-image-variable

#################################################
# Ninja
#################################################

job-debian9-ninja-gcc:
  extends: .job-ninja-gcc
  <<: *debian9-image-variable


job-debian9-ninja-clang:
  extends:
    - .job-ninja-clang
  <<: *debian9-image-variable

#################################################
# DEB
#################################################

job-debian9-deb:
  tags: [ "docker" ]
  extends: .job-linux-deb
  <<: *debian9-image-variable


job-debian9-deb-deploy:
  extends: .job-debian-deb-deploy
  variables:
    RELEASE: stretch
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  dependencies:
    - job-debian9-deb
