.archlinux-image: &archlinux-image
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION

#################################################
# Makefile
#################################################

job-archlinux-makefile-gcc:
  extends: .job-makefile-gcc
  <<: *archlinux-image


job-archlinux-makefile-clang:
  extends: .job-makefile-clang
  <<: *archlinux-image

#################################################
# Ninja
#################################################

job-archlinux-ninja-gcc:
  extends: .job-ninja-gcc
  <<: *archlinux-image


job-archlinux-ninja-clang:
  extends: .job-ninja-clang
  <<: *archlinux-image
