#################################################
# Makefile
#################################################

job-debian9-makefile-gcc:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++


job-debian9-makefile-clang:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++

#################################################
# Ninja
#################################################

job-debian9-ninja-gcc:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++


job-debian9-ninja-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .job-linux


#################################################
# DEB
#################################################

job-debian9-deb:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  extends: .job-linux-deb
  except:
    variables:
      - $DEPLOY_UBUNTU


job-debian9-deb-deploy:

  except:
    variables:
      - $DEPLOY_UBUNTU
  variables:
    RELEASE: stretch
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  extends: .job-debian-deb-deploy
  dependencies:
    - job-debian9-deb
    
    
#################################################
# Docker
#################################################

job-flexisip-debian9-image-deploy:

  dependencies:
    - job-debian9-deb
  extends: .job-flexisip-image-deploy
