.debian10-image: &debian10-image
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian10:$DEBIAN_10_IMAGE_VERSION

#################################################
# Makefile
#################################################

job-debian10-makefile-gcc:
  extends: .job-makefile-gcc
  <<: *debian10-image


job-debian10-makefile-clang:
  extends: .job-makefile-clang
  <<: *debian10-image

#################################################
# Ninja
#################################################

job-debian10-ninja-gcc:
  extends: .job-ninja-gcc
  <<: *debian10-image


job-debian10-ninja-clang:
  extends: .job-ninja-clang
  <<: *debian10-image
  variables:
    CMAKE_OPTIONS: -DENABLE_UNIT_TESTS=ON -DENABLE_UNIT_TESTS_MYSQL=ON
  artifacts:
    paths:
      - OUTPUT/*

#################################################
# DEB
#################################################

job-debian10-deb:
  tags: [ "docker" ]
  <<: *debian10-image
  extends: .job-linux-deb


job-debian10-deb-deploy:
  extends: .job-debian-deb-deploy
  variables:
    RELEASE: buster
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  dependencies:
    - job-debian10-deb

#################################################
# UNIT TESTS
#################################################

job-debian10-unit-test:
  extends: .rules-dev  # ⚠ See `rules.yml`
  stage: test
  tags: [ "docker-test" ]
  <<: *debian10-image
  needs:
    - job-debian10-ninja-clang
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib
    - export LSAN_OPTIONS="suppressions=./sanitizer_ignore.txt"
    - ./OUTPUT/bin/flexisip_tester --verbose --resource-dir ./OUTPUT/share/flexisip-tester --xml || exit $?
  artifacts:
    reports:
      junit:
        - BCUnitAutomated-Results.xml
