.job-macosx:
  stage: build
  tags: [ "macosx-xcode12" ]

  script:
    - ccache -s
    - export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
    - export MYSQL_DIR=/usr/local/opt/mysql-client
    - export CMAKE_BUILD_PARALLEL_LEVEL=$NJOBS
    - mkdir work
    - cmake -S . -B work -G "$CMAKE_GENERATOR" $DEFAULT_MACOS_CMAKE_OPTIONS $CMAKE_OPTIONS -DCMAKE_PREFIX_PATH=/usr/local/opt/mbedtls@2 -DENABLE_SOCI_POSTGRESQL_BACKEND=OFF -DENABLE_UNIT_TESTS=ON -DENABLE_UNIT_TESTS_PUSH_NOTIFICATION=OFF
    - cmake --build work -- $ADDITIONAL_BUILD_OPTIONS
    - ccache -s


.scheduled-job-macosx:

  extends: .job-macosx
  only:
    variables:
      - $NIGHTLY_MASTER
      - $NIGHTLY_RELEASE
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU

#################################################
# Makefile
#################################################

job-macosx-makefile:

  variables:
    CMAKE_GENERATOR: Unix Makefiles
    NJOBS: $MAKEFILE_JOBS
  extends: .scheduled-job-macosx

#################################################
# Ninja
#################################################

job-macosx-ninja:
  extends:
    - .job-macosx
    - .rules-dev

  variables:
    CMAKE_GENERATOR: Ninja
    NJOBS: $NINJA_JOBS

#################################################
# Xcode
#################################################

job-macosx-xcode:
  variables:
    CMAKE_GENERATOR: Xcode
    NJOBS: $MAX_NUMBER_TASK_XCODE
  extends: .scheduled-job-macosx
