#################################################
# Makefile
#################################################

job-ubuntu-18.04-makefile-gcc:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++


job-ubuntu-18.04-makefile-clang:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++

#################################################
# Ninja
#################################################

job-ubuntu-18.04-ninja-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .job-linux


job-ubuntu-18.04-ninja-clang:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  
#################################################
# DEB
#################################################

job-ubuntu-18.04-deb:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-18-04-lts:$UBUNTU_18_04_IMAGE_VERSION
  extends: .job-linux-deb
  only:
    - schedules



job-ubuntu-18.04-deb-deploy:

  variables:
    RELEASE: bionic
    FREIGHT_PATH: $UBUNTU_FREIGHT_CONF_PATH
  extends: .job-debian-deb-deploy
  dependencies:
    - job-ubuntu-18.04-deb
