#################################################
# Makefile
#################################################

job-archlinux-latest-makefile-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
  extends: .scheduled-job-linux


job-archlinux-latest-makefile-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
  extends: .scheduled-job-linux

#################################################
# Ninja
#################################################

job-archlinux-latest-ninja-gcc:
  extends:
    - .job-linux
    - .rules-dev

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++


job-archlinux-latest-ninja-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-archlinux:$ARCHLINUX_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .scheduled-job-linux
