.centos7-image-variables-before:
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-centos7:$CENTOS_7_IMAGE_VERSION
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON -DINTERNAL_JSONCPP=ON
  before_script:
    - source /opt/rh/devtoolset-8/enable

#################################################
# Makefile
#################################################

job-centos7-makefile-gcc:
  extends:
    - .job-makefile-gcc
    - .centos7-image-variables-before
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-gcc rules


job-centos7-makefile-clang:
  extends:
    - .job-makefile-clang
    - .centos7-image-variables-before
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-clang rules

#################################################
# Ninja
#################################################

job-centos7-ninja-gcc:
  extends:
    - .job-ninja-gcc
    - .centos7-image-variables-before
    - .rules-dev  # ⚠ See `rules.yml`, override .job-ninja-gcc rules

# DO NOT WORK, compilation errors
#job-centos7-ninja-clang:
#  extends:
#    - .job-ninja-clang
#    - .centos7-image-variables-before
#    - .rules-manual  # ⚠ See `rules.yml` override .job-ninja-clang rules

#################################################
# RPM
#################################################

job-centos7-rpm:
  extends:
    - .job-linux-rpm
    - .centos7-image-variables-before
    - .rules-manual # ⚠ See `rules.yml`, override .job-linux-rpm rules


job-centos7-rpm-deploy:
  extends: .job-rpm-deploy
  dependencies:
    - job-centos7-rpm
  needs:
    - job-centos7-rpm
  variables:
    DISTRIB: centos
