variables:
  ROCKY8_CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON
  ROCKY8_CMAKE_OPTIONS_UNIT_TESTS: -DINTERNAL_LIBHIREDIS=ON -DENABLE_UNIT_TESTS=ON -DENABLE_UNIT_TESTS_MYSQL=ON -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON

.rocky8-image-variables:
  image:
    name: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-rocky8:$ROCKY_8_IMAGE_VERSION
  variables:
    CMAKE_OPTIONS: ${ROCKY8_CMAKE_OPTIONS}

#################################################
# Makefile
#################################################

job-rocky8-makefile-gcc:
  extends:
    - .job-makefile-gcc
    - .rocky8-image-variables


job-rocky8-makefile-clang:
  extends:
    - .job-makefile-clang
    - .rocky8-image-variables

#################################################
# Ninja
#################################################

job-rocky8-ninja-gcc:
  extends:
    - .job-ninja-gcc
    - .rocky8-image-variables


job-rocky8-ninja-clang:
  extends:
    - .job-ninja-clang
    - .rocky8-image-variables
  variables:
    # -DCMAKE_PREFIX_PATH=/usr/local: Unit tests require libnghttp2_asio, which has been build and intalled into /usr/local
    CMAKE_OPTIONS: ${ROCKY8_CMAKE_OPTIONS_UNIT_TESTS}
  artifacts:
    paths:
      - OUTPUT/*
      - sanitizer_ignore.txt

job-rocky8-ninja-clang-nosoci:
  extends:
    - job-rocky8-ninja-clang
  variables:
    CMAKE_OPTIONS: ${ROCKY8_CMAKE_OPTIONS_UNIT_TESTS} -DENABLE_SOCI=OFF -DENABLE_B2BUA=ON -DENABLE_CONFERENCE=ON

#################################################
# UNIT TESTS
#################################################

job-rocky8-unit-test:
  extends:
    - .unit-test
    - .rocky8-image-variables
  needs:
    - job-rocky8-ninja-clang

job-rocky8-unit-test-nosoci:
  extends:
    - job-rocky8-unit-test
  needs:
    - job-rocky8-ninja-clang-nosoci

#################################################
# RPM
#################################################

job-rocky8-rpm:
  extends:
    - .job-linux-rpm
    - .rocky8-image-variables

job-rocky8-rpm-deploy:
  extends: .job-rpm-deploy
  dependencies:
    - job-rocky8-rpm
  needs:
    - job-rocky8-rpm
  variables:
    DISTRIB: rockylinux

# Test installation of the RPM package and check its feature list
job-rocky8-rpm-check-features:
  extends:
    - .rocky8-image-variables
  rules:
    - !reference [.rules-default, rules]
    - !reference [.rules-ci, rules]
  stage: deploy 🚀
  tags:
    - "docker"
  needs:
    - job-rocky8-rpm
  script:
    - sudo yum -y --nogpgcheck localinstall ./build/*.rpm
    - VERSION_STRING=$(flexisip --version)
    - echo $VERSION_STRING | grep B2BUA
    - echo $VERSION_STRING | grep Conference
    - echo $VERSION_STRING | grep Presence
    - echo $VERSION_STRING | grep Redis
    - echo $VERSION_STRING | grep RegEvent
    - echo $VERSION_STRING | grep Transcoder
    - echo $VERSION_STRING | grep Soci
