#################################################
# Makefile
#################################################

job-debian9-makefile-gcc:
  extends: .job-linux-nightly

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++


job-debian9-makefile-clang:
  extends: .job-linux-nightly

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++

#################################################
# Ninja
#################################################

job-debian9-ninja-gcc:
  extends: .job-linux-nightly

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++


job-debian9-ninja-clang:
  extends:
    - .job-linux
    - .rules-dev

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++


#################################################
# DEB
#################################################

job-debian9-deb:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  extends: .job-linux-deb
  except:
    variables:
      - $DEPLOY_UBUNTU


job-debian9-deb-deploy:
  extends: .job-debian-deb-deploy

  variables:
    RELEASE: stretch
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  dependencies:
    - job-debian9-deb

