.debian9-image-variables:
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    CMAKE_OPTIONS: -DINTERNAL_LIBHIREDIS=ON

#################################################
# Makefile
#################################################

job-debian9-makefile-gcc:
  extends:
    - .job-makefile-gcc
    - .debian9-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-gcc rules


job-debian9-makefile-clang:
  extends:
    - .job-makefile-clang
    - .debian9-image-variables
    - .rules-never-run  # ⚠ See `rules.yml`, override .job-makefile-clang rules

#################################################
# Ninja
#################################################

job-debian9-ninja-gcc:
  extends:
    - .job-ninja-gcc
    - .debian9-image-variables


job-debian9-ninja-clang:
  extends:
    - .job-ninja-clang
    - .debian9-image-variables

#################################################
# DEB
#################################################

job-debian9-deb:
  tags: [ "docker" ]
  extends:
    - .job-linux-deb
    - .debian9-image-variables
    - .rules-manual # ⚠ See `rules.yml`, override .job-linux-deb rules


job-debian9-deb-deploy:
  extends: .job-debian-deb-deploy
  variables:
    RELEASE: stretch
    FREIGHT_PATH: $DEBIAN_FREIGHT_CONF_PATH
  dependencies:
    - job-debian9-deb
  needs:
    - job-debian9-deb
