.job-macosx:
  allow_failure: true
  stage: build
  tags: [ "macosx-xcode12" ]
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU

  script:
    - ccache -s
    - export OPENSSL_ROOT_DIR=/usr/local/opt/openssl
    - export MYSQL_DIR=/usr/local/opt/mysql-client
    - export CMAKE_BUILD_PARALLEL_LEVEL=$NJOBS
    - mkdir work
    - cmake -S . -B work -G "$CMAKE_GENERATOR" $DEFAULT_MACOS_CMAKE_OPTIONS $CMAKE_OPTIONS
    - cmake --build work
    - ccache -s


.scheduled-job-macosx:

  extends: .job-macosx
  only:
    variables:
      - $NIGHTLY_MASTER
      - $NIGHTLY_RELEASE

#################################################
# Makefile
#################################################

job-macosx-makefile:

  variables:
    CMAKE_GENERATOR: Unix Makefiles
    NJOBS: $MAKEFILE_JOBS
  extends: .scheduled-job-macosx

#################################################
# Ninja
#################################################

job-macosx-ninja:
  variables:
    CMAKE_GENERATOR: Ninja
    NJOBS: $NINJA_JOBS
  extends: .job-macosx

#################################################
# Xcode
#################################################

job-macosx-xcode:
  variables:
    CMAKE_GENERATOR: Xcode
    NJOBS: $MAX_NUMBER_TASK_XCODE
  extends: .scheduled-job-macosx
