#################################################
# Makefile
#################################################

job-ubuntu-rolling-makefile-gcc:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-rolling:$UBUNTU_ROLLING_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++


job-ubuntu-rolling-makefile-clang:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-rolling:$UBUNTU_ROLLING_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++

#################################################
# Ninja
#################################################

job-ubuntu-rolling-ninja-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-rolling:$UBUNTU_ROLLING_IMAGE_VERSION
  except:
    variables:
      - $DEPLOY_RUN
      - $DEPLOY_UBUNTU
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .job-linux


job-ubuntu-rolling-ninja-clang:
  extends: .nightly-only-job-linux

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/flexisip/bc-dev-ubuntu-rolling:$UBUNTU_ROLLING_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
